version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: subscription-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: subscription_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - subscription-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d subscription_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: subscription-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5001:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - subscription-network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  subscription-network:
    driver: bridge
